### ISSUE TITLE
Close off canvas using ESC

### ISSUE THREAD

**Issue by jquimera** [cheich/Offcanvas#3]
it would be possible close the off-canvas using ESC keyboard.?

https://codepen.io/cheich/pen/XzeRdg

**Comment by cheich** [comment]
Just capture the keypress with js and call the `hide` function:

```js
  $(document).bind('keypress', function(e) {
    if ((e.keyCode || e.which) == 27) { // ESC: 27
      $("#offcanvas-box").offcanvas("hide");
    }
  });
```

New codepen: https://codepen.io/cheich/pen/JLmgLJ

**Comment by jquimera** [comment]
@cheich When we can see version 4.0. ^^

**Comment by cheich** [comment]
I'm very busy lately, but the next version is almost done. Needs some bug fixings and testings though.
